openapi: 3.2.0
x-project-name: github.com/archesai/archesai/pkg/executor
x-include-server: true
info:
  title: Arches Executor API
  description: The Arches Executor API
  version: v0.0.0
tags:
  - name: Executor
    description: Custom executor management
components:
  parameters:
    ExecutorsFilter:
      $ref: components/parameters/ExecutorsFilter.yaml
    ExecutorsSort:
      $ref: components/parameters/ExecutorsSort.yaml
  responses:
    ExecutorListResponse:
      $ref: components/responses/ExecutorListResponse.yaml
    ExecutorResponse:
      $ref: components/responses/ExecutorResponse.yaml
    SuccessfulExecutionResponse:
      $ref: components/responses/SuccessfulExecutionResponse.yaml
  schemas:
    Executor:
      $ref: components/schemas/Executor.yaml
paths:
  /executors:
    $ref: paths/executors.yaml
  /executors/{id}:
    $ref: paths/executors_id.yaml
  /executors/{id}/execute:
    $ref: paths/executors_id_execute.yaml
