description: Kubernetes resource configuration
type: object
title: ResourceConfig
properties:
  limits:
    description: Resource limits
    type: object
    properties:
      cpu:
        description: Maximum CPU allocation
        type: string
        pattern: ^\d+m?$
        default: 1000m
        minLength: 1
        example: 1000m
        maxLength: 255
      memory:
        description: Maximum memory allocation
        type: string
        pattern: ^\d+(Mi|Gi|Ki)?$
        default: 1Gi
        minLength: 1
        example: 1Gi
        maxLength: 255
    required:
      - cpu
      - memory
    additionalProperties: false
  requests:
    description: Resource requests
    type: object
    properties:
      cpu:
        description: Requested CPU allocation
        type: string
        pattern: ^\d+m?$
        default: 100m
        minLength: 1
        example: 100m
        maxLength: 255
      memory:
        description: Requested memory allocation
        type: string
        pattern: ^\d+(Mi|Gi|Ki)?$
        default: 128Mi
        minLength: 1
        example: 128Mi
        maxLength: 255
    required:
      - cpu
      - memory
    additionalProperties: false
required:
  - limits
  - requests
additionalProperties: false
x-codegen-schema-type: valueobject
