description: Billing configuration for Stripe
type: object
title: BillingConfig
properties:
  enabled:
    description: Enable billing functionality
    type: boolean
    default: false
    example: true
  stripe:
    $ref: ./ConfigStripe.yaml
required:
  - enabled
additionalProperties: false
x-codegen-schema-type: valueobject
