description: Kubernetes service account configuration
x-internal: config
type: object
title: ConfigServiceAccount
properties:
  create:
    description: Create dedicated service account
    type: boolean
    default: true
    example: true
  name:
    description: Custom service account name
    type: string
    default: ''
    example: archesai-sa
    maxLength: 255
    pattern: ^(|[a-z0-9]([-a-z0-9]*[a-z0-9])?)$
required:
  - create
  - name
additionalProperties: false
x-codegen-schema-type: valueobject
