title: ConfigAPI
description: Configuration schema for the API server
x-internal: config
type: object
properties:
  cors:
    description: A comma-separated list of allowed origins for CORS requests
    type: string
    default: localhost
    minLength: 1
    example: localhost,https://platform.archesai.com
    maxLength: 2048
    pattern: ^[\w\-\.,:/@]+$
  url:
    description: The public URL for the API
    default: http://localhost:3001
    type: string
    format: uri
    example: http://localhost:3001
    maxLength: 2048
  docs:
    description: Enable or disable API documentation
    type: boolean
    default: true
    example: true
  email:
    $ref: ./ConfigEmail.yaml
  environment:
    description: Deployment environment (development, staging, production)
    type: string
    enum:
      - development
      - staging
      - production
    default: development
    example: development
  host:
    description: The host address on which the API server will listen
    type: string
    default: 0.0.0.0
    minLength: 1
    example: 0.0.0.0
    maxLength: 255
    pattern: ^[\w\-\.:]+$
  port:
    description: The port on which the API server will listen
    type: integer
    format: int32
    minimum: 1
    maximum: 65535
    default: 3001
    example: 3001
  validation:
    description: Enable or disable request validation
    type: boolean
    default: true
    example: true
  image:
    $ref: ./ConfigImage.yaml
  resources:
    $ref: ./ConfigResource.yaml
required:
  - cors
  - docs
  - environment
  - host
  - port
  - validation
additionalProperties: false
x-codegen-schema-type: valueobject
