description: Container image configuration
x-internal: config
type: object
title: ConfigImage
properties:
  pullPolicy:
    description: Kubernetes image pull policy
    type: string
    enum:
      - Always
      - IfNotPresent
      - Never
    default: IfNotPresent
    example: Always
  repository:
    description: Container image repository
    type: string
    minLength: 1
    example: archesai/archesai
    maxLength: 255
    pattern: ^[a-z0-9]+(([._]|__|[-]+)[a-z0-9]+)*(\/[a-z0-9]+(([._]|__|[-]+)[a-z0-9]+)*)*$
  tag:
    description: Container image tag
    type: string
    default: latest
    minLength: 1
    example: v1.0.0
    maxLength: 255
    pattern: ^[a-zA-Z0-9_][a-zA-Z0-9._-]*$
required:
  - pullPolicy
  - tag
additionalProperties: false
x-codegen-schema-type: valueobject
