description: RunPod serverless GPU configuration
x-internal: config
type: object
title: ConfigRunPod
properties:
  enabled:
    description: Enable RunPod integration
    type: boolean
    default: false
    example: true
  token:
    description: RunPod API token
    type: string
    minLength: 1
    example: rp-...
    maxLength: 512
    pattern: ^[a-zA-Z0-9_\-\.]+$
required:
  - enabled
additionalProperties: false
x-codegen-schema-type: valueobject
