description: Stripe payment configuration
x-internal: config
type: object
title: ConfigStripe
properties:
  token:
    description: Stripe secret API key
    type: string
    minLength: 1
    example: sk_test_51H...
    maxLength: 512
    pattern: ^[a-zA-Z0-9_]+$
  whsec:
    description: Stripe webhook endpoint secret
    type: string
    minLength: 1
    example: whsec_...
    maxLength: 255
    pattern: ^[a-zA-Z0-9_]+$
required:
  - token
  - whsec
additionalProperties: false
x-codegen-schema-type: valueobject
