x-internal: config
type: object
title: KubernetesConfig
description: Kubernetes-specific deployment configuration
properties:
  infrastructure:
    $ref: ./ConfigInfrastructure.yaml
  ingress:
    $ref: ./ConfigIngress.yaml
  monitoring:
    $ref: ./ConfigMonitoring.yaml
additionalProperties: false
x-codegen-schema-type: valueobject
