description: Unstructured.io service for document parsing
x-internal: config
type: object
title: ConfigUnstructured
properties:
  enabled:
    description: Enable unstructured document parsing
    type: boolean
    default: false
    example: true
  managed:
    description: Use managed unstructured deployment
    type: boolean
    default: false
    example: true
  image:
    $ref: ./ConfigImage.yaml
  resources:
    $ref: ./ConfigResource.yaml
required:
  - enabled
additionalProperties: false
x-codegen-schema-type: valueobject
