description: Logging configuration
type: object
title: LoggingConfig
properties:
  level:
    description: Minimum log level to output
    type: string
    enum:
      - fatal
      - error
      - warn
      - info
      - debug
      - trace
      - silent
    default: info
    example: fatal
  pretty:
    description: Enable pretty-printed logs for development
    type: boolean
    default: false
    example: true
required:
  - level
  - pretty
additionalProperties: false
x-codegen-schema-type: valueobject
