openapi: 3.2.0
x-project-name: github.com/archesai/archesai/pkg/pipelines
x-include-server: true
info:
  title: Arches Pipelines API
  description: The Arches Pipelines API
  version: v0.0.0
tags:
  - name: Pipeline
    description: Pipeline management
  - name: Run
    description: Pipeline run management
  - name: Tool
    description: Tool management'
components:
  parameters:
    PipelinesFilter:
      $ref: components/parameters/PipelinesFilter.yaml
    PipelinesSort:
      $ref: components/parameters/PipelinesSort.yaml
    RunsFilter:
      $ref: components/parameters/RunsFilter.yaml
    RunsSort:
      $ref: components/parameters/RunsSort.yaml
    ToolsFilter:
      $ref: components/parameters/ToolsFilter.yaml
    ToolsSort:
      $ref: components/parameters/ToolsSort.yaml
  responses:
    PipelineExecutionPlanResponse:
      $ref: components/responses/PipelineExecutionPlanResponse.yaml
    PipelineListResponse:
      $ref: components/responses/PipelineListResponse.yaml
    PipelineResponse:
      $ref: components/responses/PipelineResponse.yaml
    PipelineStepListResponse:
      $ref: components/responses/PipelineStepListResponse.yaml
    PipelineStepResponse:
      $ref: components/responses/PipelineStepResponse.yaml
    RunListResponse:
      $ref: components/responses/RunListResponse.yaml
    RunResponse:
      $ref: components/responses/RunResponse.yaml
    ToolListResponse:
      $ref: components/responses/ToolListResponse.yaml
    ToolResponse:
      $ref: components/responses/ToolResponse.yaml
  schemas:
    Pipeline:
      $ref: components/schemas/Pipeline.yaml
    PipelineStep:
      $ref: components/schemas/PipelineStep.yaml
    Run:
      $ref: components/schemas/Run.yaml
    Tool:
      $ref: components/schemas/Tool.yaml
paths:
  /pipelines/{id}/execution-plans:
    $ref: paths/pipelines_id_execution-plans.yaml
  /pipelines/{id}/steps:
    $ref: paths/pipelines_id_steps.yaml
  /pipelines/{id}:
    $ref: paths/pipelines_id.yaml
  /pipelines:
    $ref: paths/pipelines.yaml
  /runs/{id}:
    $ref: paths/runs_id.yaml
  /runs:
    $ref: paths/runs.yaml
  /tools/{id}:
    $ref: paths/tools_id.yaml
  /tools:
    $ref: paths/tools.yaml
