description: Current configuration
content:
  application/json:
    schema:
      description: Configuration object
      type: object
      properties:
        data:
          $ref: ../schemas/config/Config.yaml
headers:
  X-RateLimit-Limit:
    $ref: ../../../../../apis/base/api/components/headers/RateLimitLimit.yaml
  X-RateLimit-Remaining:
    $ref: ../../../../../apis/base/api/components/headers/RateLimitRemaining.yaml
  X-RateLimit-Reset:
    $ref: ../../../../../apis/base/api/components/headers/RateLimitReset.yaml
