x-path: /config
get:
  x-internal: config
  x-codegen-custom-handler: true
  operationId: GetConfig
  summary: Get the configuration
  tags:
    - Config
  description: Get the configuration of the application
  responses:
    '200':
      $ref: ../components/responses/ConfigResponse.yaml
    '400':
      $ref: ../components/responses/BadRequest.yaml
    '401':
      $ref: ../components/responses/Unauthorized.yaml
    '422':
      $ref: ../components/responses/UnprocessableEntity.yaml
    '429':
      $ref: ../components/responses/TooManyRequests.yaml
    '500':
      $ref: ../components/responses/InternalServerError.yaml
  security:
    - {}
