name: Docker Build and Push

on:
  workflow_call:
    inputs:
      service:
        description: 'Name of the service to build and tag (e.g., api, platform)'
        required: true
        type: string

env:
  GCP_PROJECT_ID: archesai

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: google-github-actions/auth@v3
        id: auth
        with:
          token_format: access_token
          workload_identity_provider: projects/1080946766516/locations/global/workloadIDentityPools/github/providers/my-repo
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account: github-actions-artifact-regist@archesai.iam.gserviceaccount.com

      - uses: google-github-actions/setup-gcloud@v3

      - uses: docker/login-action@v3
        with:
          registry: us-east4-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - id: prev-commit
        run: |
          PREV_COMMIT=$(git rev-list -n 1 HEAD^1)
          echo "PREV_COMMIT=$PREV_COMMIT" >> $GITHUB_ENV

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          base: ${{ env.PREV_COMMIT }}
          filters: |
            service:
              - '${{ inputs.service }}/**'

      - if: steps.changes.outputs.service == 'true'
        uses: docker/setup-buildx-action@v3

      - if: steps.changes.outputs.service == 'true'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: us-east4-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/images/${{ inputs.service }}:latest
          cache-from: type=registry,ref=us-east4-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/images/${{ inputs.service }}:buildcache
          cache-to: type=registry,ref=us-east4-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/images/${{ inputs.service }}:buildcache,mode=max
          context: '{{defaultContext}}:${{ inputs.service }}'

      - run: |
          gcloud container images add-tag \
            us-east4-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/images/${{ inputs.service }}:latest \
            us-east4-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/images/${{ inputs.service }}:${{ github.sha }}
